# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscription_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(default=django.utils.timezone.now, max_length=254)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(default=0)),
                ('telephone', models.CharField(max_length=10)),
                ('guests', models.IntegerField()),
            ],
        ),
    ]
